### ISSUE TITLE
botAccountCreate.py keeps crashing

### ISSUE THREAD

**Issue by ghost** [Alan4747/instagram-auto-create-account#1]
I suggest you put this code unstead //*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[7]/div/button
The old one was doing some problems . And it's outdated i think , Instagram keeps requesting phone number...

**Comment by minoundseineak** [comment]
browser= webdriver.Chrome(executable_path=r'you path\chromedriver.exe')
