### ISSUE TITLE
Not valid verification code

### ISSUE THREAD

**Issue by federicoromeo** [Alan4747/instagram-auto-create-account#10]
I was kinda doing the same project as this one (selenium, chromedriver), the only last problem is that when i try to put the verification code received by email, instagram tells me "code not valid, try requesting a new one". 
Trying to put the code manually and click manually it works just fine, but when i leave my script doing it, instagram will block it!

Do you know what i can do?
(I'll leave this repo a star ;) )

**Comment by rubic0nexe** [comment]
It doesnt work for me when i type it myself even, but the script works, any help?

**Comment by federicoromeo** [comment]
the script works doing what?

**Comment by Alan4747** [comment]
I guess this problem is solved. @ManWuzi  Thank you.

**Comment by federicoromeo** [comment]
so you suggest to ask for a new code when the first fails?

**Comment by federicoromeo** [comment]
so you suggest to: ask the code, insert and submit, see the error, ask a new code, insert and submit again?
edit: i tried and fails again

**Comment by ManWuzi** [comment]
Strange. I tried it and it worked when i manually did it but not in code. I'll try to work on the code later to implement it

**Comment by plexab** [comment]
I have this only on some proxies
I don’t know how to fix it ((

maybe it's protection against suspicious activity when registering

**Comment by federicoromeo** [comment]
@ManWuzi yes the problem is exactly the automation, doing it manually it's obviously fine
