### ISSUE TITLE
"That code isn't valid. You can request a new one."

### ISSUE THREAD

**Issue by rubic0nexe** [Alan4747/instagram-auto-create-account#11]
As in title, instagram says this when trying to register account. So far i tried: Proxy, Residential VPN.
That didn't work tho.
Could you make some patch please?

**Comment by drdoof2019** [comment]
I  tried with my hand but email did not work for me too. 
I received conf. message but instagram understand that its a fake e-mail

**Comment by Alan4747** [comment]
It has been resolved in the last update.
