### ISSUE TITLE
How can i avoid phone number authentication

### ISSUE THREAD

**Issue by BbChip0103** [Alan4747/instagram-auto-create-account#18]
Hi there. 
Actually it's not defect of this repository. But I'm sure that many people faced this issue like me.
Creating account code worked well. So i tried to make several account, 
But when i made 3rd account by the code,  instagram require me additional phone number authentication.
I already tried free proxy or VPN, but most of them didn't work and few of them worked just 1,2 times.

I need your help. Is anybody have solution of this?
If you don't have any solution, we need to discuss or guess or anything.

**Comment by Alan4747** [comment]
@BbChip0103 I am working on this too. I still haven't found a solution. Let's find a solution to this together.

**Comment by haniyadav** [comment]
use user agent changer

from selenium.webdriver.chrome.options import Options
from fake_useragent import UserAgent
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent={userAgent}')
driver = webdriver.Chrome(options=options, executable_path=r"C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe")
driver.get("https://www.instagram.com/accounts/emailsignup/")
time.sleep(8)
rest of the program.............
but you will have to replace 'browser' word everywhere with 'driver'. It worked perectly for me... It helped me creating 50 account hour.

**Comment by Alan4747** [comment]
@haniyadav Yes, it worked very well. I tried it too. Thank you very much for your support.
