### ISSUE TITLE
Is it work?

### ISSUE THREAD

**Issue by nikoomaram** [Alan4747/instagram-auto-create-account#4]
Hi, this code is it work today?

**Comment by Alan4747** [comment]
Hi, Yes it is working.

nikoomaram <notifications@github.com>, 5 Tem 2020 Paz, 13:22 tarihinde şunu
yazdı:

**Comment by Alan4747** [comment]
I haven't tried it in a very short time, but it works

Alan HAMMOUD <alan47m@gmail.com>, 5 Tem 2020 Paz, 23:44 tarihinde şunu
yazdı:

**Comment by nigarnm** [comment]
Merhaba arkadas Lutfen nasil calisdigini anlatmak icin iletisime gece bilirmisin ? +994552090818
