### ISSUE TITLE
30 days account block

### ISSUE THREAD

**Issue by vladkrtv15** [Alan4747/instagram-auto-create-account#51]
Hey. When automation is finished I'm getting an error saying that Account will be blocked for 30 days. Any ideas to solve this? - Tried adding more time between time.sleep() like 60 - 120 seconds but still not working, I'm thinking this may be because of the domain provider of the email? Thank you.

**Comment by ring0jke** [comment]
Have same issue btw.

Seems like insta detecting selenium somehow

**Comment by pokzy** [comment]
use vpn/proxy.
