### ISSUE TITLE
Adding options for chromedriver in Ubuntu 

### ISSUE THREAD

**Issue by juanignaciociriaco** [Alan4747/instagram-auto-create-account#9]
Hi guys,
Just add these lines into botAccountCreate.py:

chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument('--disable-gpu')
browser= webdriver.Chrome(options=chrome_options, executable_path='/usr/bin/chromedriver')

**Comment by Alan4747** [comment]
I did not add this code as it will not work on all operating systems. Only works on ubuntu.
